stages:
    - check
    - build
lint:
  stage: check
  script:
    - npm i
    - node_modules/eslint/bin/eslint.js .
build:
  stage: build
  needs: 
    - lint
  before_script:
    - docker info
  script:
    - docker build -t blob-bot .