stages:
  - lint
  - build

lint: 
    image: node
    stage:
     - lint
    eslint:
     stage: lint
     script:
        - npm i eslint
        - npm i
        - node_modules/eslint/bin/eslint.js .
build_image:
    stage:
     - build
    eslint:
     stage: lint
     before_script:
        - docker info
     script:
        - docker build -t blob-bot .