stages:
    - check
    - build
    - test
    - push
eslint:
    stage: check
    script:
        - npm i
        - node_modules/eslint/bin/eslint.js .
build_container:
    stage: build
    needs: 
        - eslint
    before_script:
        - docker info
    script:
        - docker build -t ryois/blob-bot .
run_container:
    stage: test
    needs: 
        - eslint
        - build_container
    script:
        - docker run ryois/blob-bot -env TOKEN=$TOKEN -env PREFIX=$PREFIX
push_dockerhub:
    stage: push
    needs: 
        - eslint
        - build_container
        - run_container
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - docker push "$CI_REGISTRY_IMAGE"
