stages:
    - check
    - build
    - test
eslint:
    stage: check
    script:
        - npm i
        - node_modules/eslint/bin/eslint.js .
build_container:
    stage: build
    needs: 
        - eslint
    before_script:
        - docker info
    script:
        - docker build -t ryois/blob-bot .
run_container:
    stage: test
    needs: 
        - eslint
        - build_container
    script:
        - docker run -e CI=true  ryois/blob-bot npm run test
