stages:
    - check
    - build
    - test
eslint:
    stage: check
    script:
        - npm i
        - node_modules/eslint/bin/eslint.js .
build:
    stage: build
    needs: 
        - eslint
    script:
        - docker build -t ryois/blob-bot:latest .
test:
    stage: test
    needs: 
        - eslint
        - build
    script:
        - docker run -e CI=true  ryois/blob-bot npm run test